### ISSUE TITLE
OANDA海外での使用

### ISSUE THREAD

**Issue by pr0ndisk** [unageanu/jiji2#327]
OANDAJapanとはAPIの仕様が異なるのでしょうか？
試しにTokenを入力してみたのですが、動作しないようです。

**Comment by unageanu** [comment]
未確認ではありますが、動作するはず、という認識です。
ただ、今見ると oanda.com では v20 REST API がリリースされているので、新API専用のアカウントになっているのかもしれません。

**Comment by pr0ndisk** [comment]
v20 REST APIだと動作しない？
ヨーロッパのアカウントですと貴金属やCFDも同時にトレード出来るので、色々と捗るなあと思ったのですが、、、
とりあえず最近JAPANのアカウントも作って、Herokuにインストールしての利用です。
非常にイイ！ありがとうございます。

**Comment by pr0ndisk** [comment]
只今確認しましたところ、注文が通っていました。
ただ、
E, [2017-08-04T21:13:54.837878 #4] ERROR -- : Jiji::Errors::NotInitializedException (Jiji::Errors::NotInitializedException)
/app/src/jiji/errors/errors.rb:77:in `not_initialized'
/app/src/jiji/model/securities/nil_securities.rb:9:in `method_missing'
/app/src/jiji/model/trading/brokers/abstract_broker.rb:30:in `tick'
/app/src/jiji/model/trading/brokers/abstract_broker.rb:152:in `refresh'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:22:in `before_do_next'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:16:in `exec'
/app/src/jiji/model/trading/process.rb:37:in `do_next_job'
/app/src/jiji/model/trading/process.rb:30:in `run'
/app/src/jiji/model/trading/process.rb:24:in `block in start'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'

こういったエラーがログに出ていました。

**Comment by unageanu** [comment]
このエラーは、アクセストークン未設定(=初期設定が完了していない)の状態でJijiを起動している場合に表示されるエラーですね。アクセストークン設定後(=初期設定が完了後)は表示されなくなるはずです。

**Comment by pr0ndisk** [comment]
CFDの取引なのですがT-BOND(USB30YUSD)を取引しようとすると以下のエラーが出ます。

E, [2017-08-04T22:10:58.437399 #4] ERROR -- : counter pair is not found. pair=30YUUSD (RuntimeError)
/app/src/jiji/model/trading/utils/counter_pair_resolver.rb:57:in `resolve_required_pairs'
/app/src/jiji/model/trading/utils/counter_pair_resolver.rb:45:in `resolve_rate'
/app/src/jiji/model/trading/utils/counter_pair_resolver.rb:72:in `resolve_rate'
/app/src/jiji/model/trading/utils/pricing_utils.rb:22:in `calculate_current_counter_rate'
/app/src/jiji/model/trading/internal/position_internal_functions.rb:39:in `update_price'
/app/src/jiji/model/trading/positions.rb:43:in `block in update_price'
/app/src/jiji/model/trading/positions.rb:41:in `each'
/app/src/jiji/model/trading/positions.rb:41:in `update_price'
/app/src/jiji/model/trading/brokers/abstract_broker.rb:152:in `refresh'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:22:in `before_do_next'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:16:in `exec'
/app/src/jiji/model/trading/process.rb:37:in `do_next_job'
/app/src/jiji/model/trading/process.rb:30:in `run'
/app/src/jiji/model/trading/process.rb:24:in `block in start'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'

**Comment by unageanu** [comment]
これはJiji側の問題ですね。
為替以外の商品に対応していない箇所があるようです。

**Comment by pr0ndisk** [comment]
貴金属も駄目みたいです。(XAGJPY、SilverJPY共に)あとは取引状況が常に【サーバーが混雑しています。しばらく待ってからやり直してください。】状態です。現在日本居住者は海外OANDAの口座開設が出来ないようなので、対応は難しいですよね？

でもFXの取引が自動化出来るだけでも有難やです。

**Comment by unageanu** [comment]
> 対応は難しいですよね？
需要が多ければ対応を検討したいところです。

**Comment by pr0ndisk** [comment]
非通貨ペア(CFD、貴金属)の読み込みのエラーで動作が不安定になるようです。
Herokuにインストールして稼働させていたのですが、
【サーバーが混雑しています。しばらく待ってからやり直してください。】のメッセージが頻発して、発注が為されなかったり、クラッシュしてしまったり。

今は、Windows10上のCentos7(Hyper-V)にて、
CFDのポジションを解消して、通貨のみで稼働させると問題なく動作しております。

**Comment by unageanu** [comment]
ログには、以下以外のエラーは出力されていないでしょうか?

```
E, [2017-08-04T22:10:58.437399 #4] ERROR -- : counter pair is not found. pair=30YUUSD (RuntimeError)
/app/src/jiji/model/trading/utils/counter_pair_resolver.rb:57:in resolve_required_pairs' 
/app/src/jiji/model/trading/utils/counter_pair_resolver.rb:45:inresolve_rate'
/app/src/jiji/model/trading/utils/counter_pair_resolver.rb:72:in resolve_rate' /app/src/jiji/model/trading/utils/pricing_utils.rb:22:incalculate_current_counter_rate'
/app/src/jiji/model/trading/internal/position_internal_functions.rb:39:in update_price' /app/src/jiji/model/trading/positions.rb:43:inblock in update_price'
/app/src/jiji/model/trading/positions.rb:41:in each' 
....
```

ありそうなのは、エラーの影響でどこかでメモリリークが発生しているパターンですかね。

**Comment by pr0ndisk** [comment]
他に表示は無かったかと思われます。
ほぼコレでログ画面が埋め尽くされるような感じです(汗

**Comment by pr0ndisk** [comment]
為替のみトレードだとOANDA Europeでも安定して動いています。
やっぱり、貴金属やCFDのポジションがあるとそれが悪さをするみたいです。

USB30YUSD→30YUUSDとして正しく認識してくれないのが原因でしょうか？
でも、設定画面の通貨ペアの設定を見ると表示は正しいようですが。

**Comment by unageanu** [comment]
情報ありがとうございます。

> USB30YUSD→30YUUSDとして正しく認識してくれないのが原因でしょうか？
何とも言えませんが、その可能性は高そうですね。

**Comment by JunyaW** [comment]
途中から失礼致します。海外居住者なのですが、oanda.comでのjijiの利用を考えていました。

現在、oanda.comのFXtradeのpractice accountのAPIのアクセストークンを発行し、
jiji内の証券会社の設定の箇所に入れてみたところ、
「証券会社に接続できませんでした。アクセストークンを確認してください。」
とのコメントが出ました。（ちなみに使用する証券会社の欄はoanda japan demoにしてみました。）

昨年のお二人の会話から、oanda.comでもjijiが利用出来ると思っていたのですが、なにか特殊な設定などが必要なのでしょうか？

お手数をおかけしますが、回答宜しくお願い致します。

**Comment by unageanu** [comment]
oanda.com は v20 REST API に移行しているようなので、新規作成したアカウントだと動作しないかもしれません。Jijiは v1 REST API にのみ対応しています。

**Comment by JunyaW** [comment]
確認したところ、ご指摘の通りのようです。回答ありがとうございました。
