### ISSUE TITLE
Sometimes spec failed for illegal time period.

### ISSUE THREAD

**Issue by janckerchen** [unageanu/jiji2#387]
not always

```
  2) Jiji::Model::Trading::BackTestRepository テストが3つ登録されている場合 テストで利用しているエージェントが削除されていた場合も、正しく起動できる
     Failure/Error: @repository.load

     ArgumentError:
       illegal period. start_time=2015-12-09 04:00:00 UTC end_time=2015-12-09 12:00:00 +0800
     # /opt/dev/+github/unageanu/jiji2/src/jiji/errors/errors.rb:99:in `illegal_argument'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/securities/internal/virtual/rate_retriever.rb:66:in `check_period'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/securities/internal/virtual/rate_retriever.rb:12:in `init_rate_retriever_state'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/securities/virtual_securities.rb:26:in `initialize'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/brokers/back_test_broker.rb:55:in `new'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/brokers/back_test_broker.rb:55:in `build_components'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/brokers/back_test_broker.rb:25:in `initialize'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/back_test.rb:218:in `new'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/back_test.rb:218:in `create_broker'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/back_test.rb:205:in `create_components'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/back_test.rb:133:in `setup'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/back_test_repository.rb:122:in `setup_backtest'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/back_test_repository.rb:93:in `block in load'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/back_test_repository.rb:92:in `each_with_object'
     # /opt/dev/+github/unageanu/jiji2/src/jiji/model/trading/back_test_repository.rb:92:in `load'
     # /opt/dev/+github/unageanu/jiji2/spec/jiji/model/trading/back_test_repository_spec.rb:509:in `block (3 levels) in <top (required)>'

```

**Comment by unageanu** [comment]
It seems that the result has changed depending on the processing status of the backtest running in another thread.I intended to fix them all, but it seems to be still there...

**Comment by janckerchen** [comment]
yes,  another failed is about backtest status.

```
 1) Jiji::Model::Trading::BackTestRepository テストが3つ登録されている場合 追加したテストは永続化され、再起動時に読み込まれる
     Failure/Error: expect(status[:status]).to eq :running

       expected: :running
            got: :wait_for_finish

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:running
       +:wait_for_finish

```

**Comment by unageanu** [comment]
Thanks for reporting. It seems like the same problem.
