### ISSUE TITLE
リアルトレードとバックテスト実施中にMongoDBのエラーが発生しました

### ISSUE THREAD

**Issue by nonoichi123** [unageanu/jiji2#427]
Heroku の環境で利用しているのですが、
リアルトレード実施しながら、バックテストを実施していたところ、
MongoDBで、以下のエラーが発生しました。

エラーの解消ができない状態でして、
解消方法を教えていただけないでしょうか。

### バックテストのログ

```
E, [2017-12-07T18:20:51.189532 #4] ERROR -- : Mongo::Error::BulkWriteError (Mongo::Error::BulkWriteError)
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/bulk_write/result.rb:184:in `validate!'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/bulk_write/result_combiner.rb:73:in `result'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/bulk_write.rb:65:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/collection.rb:385:in `bulk_write'
/app/src/jiji/utils/bulk_write_operation_support.rb:86:in `execute_bulk_write_operations'
/app/src/jiji/utils/bulk_write_operation_support.rb:66:in `execute'
/app/src/jiji/utils/bulk_write_operation_support.rb:23:in `end_transaction'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:104:in `refresh_transaction'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:76:in `exec'
/app/src/jiji/model/trading/process.rb:37:in `do_next_job'
/app/src/jiji/model/trading/process.rb:30:in `run'
/app/src/jiji/model/trading/process.rb:24:in `block in start'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'
```

### リアルトレードのログ

```
E, [2017-12-07T18:25:44.877935 #4] ERROR -- : quota exceeded (12501) (Mongo::Error::OperationFailure)
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/operation/result.rb:256:in `validate!'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/operation/write/insert.rb:55:in `execute_write_command'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/operation/write/write_command_enabled.rb:38:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/collection.rb:346:in `block in insert_one'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/retryable.rb:112:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/retryable.rb:112:in `write_with_retry'
/app/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.7/lib/mongo/collection.rb:337:in `insert_one'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/query_cache.rb:168:in `insert_one_with_clear_cache'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/persistable/creatable.rb:79:in `insert_as_root'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/persistable/creatable.rb:27:in `block in insert'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/persistable/creatable.rb:118:in `block (2 levels) in prepare_insert'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/persistable/creatable.rb:117:in `block in prepare_insert'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/persistable/creatable.rb:23:in `insert'
/app/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/persistable/savable.rb:23:in `save'
/app/src/jiji/utils/bulk_write_operation_support.rb:9:in `save'
/app/src/jiji/model/graphing/internal/graph_data_saver.rb:27:in `recreate_graph_data'
/app/src/jiji/model/graphing/internal/graph_data_saver.rb:19:in `save_data_if_required'
/app/src/jiji/model/graphing/graph.rb:79:in `block in save_data'
/app/src/jiji/model/graphing/graph.rb:78:in `each'
/app/src/jiji/model/graphing/graph.rb:78:in `save_data'
/app/src/jiji/model/graphing/graph_factory.rb:40:in `block in save_data'
/app/src/jiji/model/graphing/graph_factory.rb:39:in `each'
/app/src/jiji/model/graphing/graph_factory.rb:39:in `save_data'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:53:in `save_graph_data'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:29:in `after_do_next'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:18:in `exec'
/app/src/jiji/model/trading/process.rb:37:in `do_next_job'
/app/src/jiji/model/trading/process.rb:30:in `run'
/app/src/jiji/model/trading/process.rb:24:in `block in start'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'
```

よろしくお願いいたします。

**Comment by unageanu** [comment]
`quota exceeded` なので、何らかのリミットに達したものと思われます。
一番怪しいのはMongoDBの容量不足なので、不要なバックテストを削除することで解消されないでしょうか?

**Comment by nonoichi123** [comment]
早速のご返信、ありがとうございます。

バックテストを何度か実行しようとしたことで、
mongoDBの容量不足が解消したようで、
再実行できるようになりました。

不要なバックテストを削除して、
対応するようにいいたします。
