### ISSUE TITLE
[include Mongoid::Document]でエラーが発生

### ISSUE THREAD

**Issue by tisakiras** [unageanu/jiji2#510]
エージェントのソースに[include Mongoid::Document]の記述がある状態で［テストの作成］をクリックすると「サーバーが混雑しています。しばらく待ってからやり直してください」となります。
100%の再現性があり、この一文だけのクラスを登録しても再現します。
どなたかアドバイスをお願いします。

なお、jijiのログには以下のエラーが出ていました。（的外れだったらスイマセン）

E, [2019-12-19T09:09:25.522879 #1] ERROR -- : uninitialized constant Module::AgentBuilder (NameError)
/app/jiji2/src/jiji/model/agents/internal/agent_finder.rb:61:in `const_get'
/app/jiji2/src/jiji/model/agents/internal/agent_finder.rb:61:in `block in find_agent'
/app/jiji2/src/jiji/model/agents/internal/agent_finder.rb:60:in `each'
以下略

**Comment by david-daisuke** [comment]
私も同様のエラーがでます。何か解決策をご存じの方はご連絡いただければとおもいます。
